### ISSUE TITLE
Add BannerCLI

### ISSUE THREAD

**Issue by cjpatoilo** [vinicius73/awesome-brasil#21]
[BannerCLI](https://github.com/cjpatoilo/banner-cli)

> Create a banner comment from package data.

A command line interface to add relevant information to your source code from package data. This lib reads the `package.json` files, then a banner is generated based on each of these values: `name`, `version`, `homepage`, `year`, `author` and `license`.

**Comment by vinicius73** [comment]
Pode mandar PR diretamente :)
